# config.yaml
# Configuration file for the system
# Can choose logs folder, log details activation, enabled actuators, buffering parameters
#
# Author: Francesco Urru
# Github: https://github.com/frarvo
# Repository: https://github.com/frarvo/CPSA_2026
# License:

log_base_path: ~/Desktop/CPSA_logs  # Path where logs are saved. User folder is automatically detected

enable_system_log: true      # Create/Log system status messages
enable_actuation_detail: false  # Log actuation used for that event

debug_system_console: true   # Choose to print system events on the console
debug_event_console: true    # Choose to print events on the console

metamotion:
  enable: true                # Device activation flag
  scan_timeout: 2             # First scan duration in seconds
  fast_retry_attempts: 5      # Number of fast retries after a disconnection
  retry_interval: 5           # Wait time between fast retries
  retry_sleep: 60             # Wait time between subsequent retries

speaker:
  mac: D4:8C:49:C9:DC:9A      # Device MAC address
  enable: false                # Device activation flag
  scan_timeout: 5             # First scan duration in seconds
  fast_retry_attempts: 5      # Number of fast retries after a disconnection
  retry_interval: 10          # Wait time between fast retries
  retry_sleep: 60             # Wait time between subsequent retries

led_strip:
  enable: false               # Device activation flag
  duration: 2500              # Duration in ms
  scan_timeout: 10            # First scan duration in seconds
  fast_retry_attempts: 5      # Number of fast retries after a disconnection
  retry_interval: 5           # Wait time between fast retries
  retry_sleep: 60             # Wait time between subsequent retries

policy:
  attempts: 3         # Number of attempts with the same actuator before changing it

event_queue_size: 1

yolo_model_name: "/home/ubuntu/Desktop/PROJECT_CPSA_2026/VIDEO_pipeline/YOLO/pynqdpu.tf_yolov3_voc.DPUCZDX8G_ISA1_B4096.2.5.0.xmodel"
movenet_model_name: "/home/ubuntu/Desktop/PROJECT_CPSA_2026/VIDEO_pipeline/MOVENET/kv260_MoveNet_int.xmodel"

